server:
  port: 8060

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: authentication
          uri: lb://AUTHENTICATION
          predicates:
            - Path=/api/auth/**

        - id: authentication
          uri: lb://AUTHENTICATION
          predicates:
            - Path=/api/v1/roles/**
          filters:
            - AuthenticationFilter

        - id: authentication
          uri: lb://AUTHENTICATION
          predicates:
            - Path=/api/v1/permissions/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

#management:
#  tracing:
#    sampling:
#      probability: 1.0